version: '3'
services:
  nginx:
    depends_on:
      - client
      - server
    restart: always
    build: 
      dockerfile: Dockerfile
      context: ./nginx
    image: rishabh2974/nginx:latest
    ports:
      - '80:80'
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: rishabh2974/client:latest
    restart: on-failure
    container_name: client
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: rishabh2974/server:latest
    restart: on-failure
    container_name: server