version: '3'
services:
  nginx:
    depends_on:
      - client
      - server
    restart: always
    build: 
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '80:80'
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: on-failure
    container_name: client
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: on-failure
    container_name: server
    env_file:
      - ./server/server.env